### ISSUE TITLE
surface() causes kernel to die

### ISSUE THREAD

**Issue by rantahar** [AaltoRSE/julia-introduction#1]
In exercise 6, the plotting exercise suggests running surface(). This causes the kernel to die on my laptop without a good error message.

I should investigate this.

**Comment by lucaferranti** [comment]
for what is worth, it works for me (julia 1.6.0) with both gr and plotlyjs backend.

**Comment by rantahar** [comment]
Also works for me after updating to 1.6.0. Closing this now but I need to keep this in mind.
